name: Notify Docs-triagers

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Notify-triagers:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Changes
        id: pr-changes
        run: |
          md_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || true)
          echo "::set-output name=md_changes::${md_files}"

      - name: Create Comment
        if: steps.pr-changes.outputs.md_changes != ''
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message: "This is a test comment to check workflow for changes to Markdown files."
          repo-token: ${{ secrets.GH_TOKEN }}