name: Notify Docs-triagers

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Notify-triagers:
    runs-on: ubuntu-latest
    steps:
        - name: Check PR Changes
          id: pr-changes
          run: echo "::set-output name=changes::${{ toJson(github.event.pull_request.changed_files) }}"
        
        - name: Create Comment
          if: steps.pr-changes.outputs.changes != '[]'
          uses: mb2dev/github-action-comment-pull-request@1.0.0
          with:
            message: "This is a test comment to check workflow"
            GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
            
