name: Notify Docs-triagers

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Notify-triagers:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Get PR Files
          uses: tj-actions/changed-files@v42.0.2
          with: 
            files: |
              **.md
        - name: Create Comment on Pull request
          if: steps.changed-markdown-files.outputs.any_changed == 'true'
          uses: mshick/add-pr-comment@v2.8.2
          with:
            message: "This is a test comment to check workflow for docs changes"
            repo-token: ${{secrets.GH_TOKEN}}
