name: Notify Docs-triagers

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Notify-triagers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check PR Changes
        id: pr-changes
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **.md

      - name: Create Comment
        if: steps.pr-changes.outputs.any_changed == 'true'
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message: "This is a test comment to check workflow for changes to Markdown files."
          repo-token: ${{ secrets.GH_TOKEN }}
